<a href="https://colab.research.google.com/github/adnanhussai9/FSDS-Assignment/blob/main/Python_Basic_Programming_Assignment/Pr_Assignment_8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Programming Assignment 8

1. Write a Python Program to Add two Matrices ?

In [3]:
import numpy as np
def addMatrices(arr1, arr2):
  array1 = np.array(arr1)
  array2 = np.array(arr2)
  print(array1 + array2)

addMatrices([[1, 2, 3], [4, 5, 6], [7, 8, 9]],[[9, 8, 7], [6, 5, 4], [3, 2, 1]])

[[10 10 10]
 [10 10 10]
 [10 10 10]]


2. Write a Python Program to Multiply two Matrices ?

In [5]:
import numpy as np
def mulMatrices(arr1, arr2):
  array1 = np.array(arr1)
  array2 = np.array(arr2)
  print(np.matmul(array1, array2))

a = [[1,2,3],[4,5,6],[7,8,9]]
b = [[1,4,7],[2,5,8],[3,6,9]]
mulMatrices(a, b)

[[ 14  32  50]
 [ 32  77 122]
 [ 50 122 194]]


3. Write a Python Program to transpose a Matrix ?

In [6]:
import numpy as np
def transMatrices(arr):
  array = np.array(arr)
  print(np.transpose(array))

a = [[1,2,3],[4,5,6],[7,8,9]]
transMatrices(a)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


4. Write a Python Program to sort Words in an Alphabatical Order ?

In [7]:
def sortString():
    in_string = input("Enter a String: ").title()
    sorted_list = sorted(in_string.split(' '))
    print(' '.join(sorted_list))

sortString()

Enter a String: Syed Adnan Hussain
Adnan Hussain Syed


5. Write a Python Program to remove Punctuations From a String ?

In [8]:
def removePunctuatuions():
    punctuations = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''
    in_string = input('Enter a String: ')
    out_string = ''
    for ele in in_string:
        if ele not in punctuations:
            out_string += ele
    print(out_string)

removePunctuatuions()

Enter a String: I said, "Good Morning!"
I said Good Morning
